<?php
/**
 * Please, do not edit this file. The configuration file for Debian system
 * is located at /etc/phpmyadmin directory.
 */
include('/etc/phpmyadmin/blowfish_secret.inc.php');
$cfg['Servers'][1]['host'] = 'localhost';
$cfg['Servers'][1]['connect_type']  = 'socket';
$cfg['Servers'][1]['auth_type'] = 'cookie';
if (!defined('PMA_VERSION')) {
    define('PMA_VERSION', '@VERSION@');
}
include('/etc/phpmyadmin/config.inc.php');
?>
