<?php
require_once 'PhpMyAdmin/MoTranslator/autoload.php';
require_once 'PhpMyAdmin/ShapeFile/autoload.php';
require_once 'PhpMyAdmin/SqlParser/autoload.php';
require_once 'Symfony/Component/ExpressionLanguage/autoload.php';
require_once 'phpseclib/autoload.php';
require_once 'Twig/autoload.php';
require_once 'ReCaptcha/autoload.php';
require_once 'Psr/Container/autoload.php';

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                ___CLASSLIST___
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require ___BASEDIR___ $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
