#!/bin/sh

set -e

. /usr/share/debconf/confmodule
db_version 2.0

db_input high phpmyadmin/reconfigure-webserver || true

if [ ! -f /etc/phpmyadmin/htpasswd.setup ]; then
	db_input low phpmyadmin/setup-username || true
	db_input low phpmyadmin/setup-password || true
fi

db_go || true

