#!/bin/sh
# preinst script for phpmyadmin

set -e

# move blowfish secret from /etc to /var/. Can be removed after lenny.
if [ "$1" = "upgrade" ] && dpkg --compare-versions "$2" lt 4:2.10.0.2-1 &&
	[ -e /etc/phpmyadmin/blowfish_secret.inc.php ]; then
	mv /etc/phpmyadmin/blowfish_secret.inc.php \
		/var/lib/phpmyadmin/
fi
		


#DEBHELPER#

exit 0


